# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(700, 600)
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 700, 600))
        self.label.setObjectName("label")
        self.button_hybrid = QtWidgets.QPushButton(self.centralwidget)
        self.button_hybrid.setGeometry(QtCore.QRect(620, 70, 75, 23))
        self.button_hybrid.setObjectName("button_hybrid")
        self.button_scheme = QtWidgets.QPushButton(self.centralwidget)
        self.button_scheme.setGeometry(QtCore.QRect(620, 40, 75, 23))
        self.button_scheme.setObjectName("button_scheme")
        self.button_sat = QtWidgets.QPushButton(self.centralwidget)
        self.button_sat.setGeometry(QtCore.QRect(620, 10, 75, 23))
        self.button_sat.setObjectName("button_sat")
        Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window)
        self.statusbar.setObjectName("statusbar")
        Window.setStatusBar(self.statusbar)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "MainWindow"))
        self.label.setText(_translate("Window", "TextLabel"))
        self.button_hybrid.setText(_translate("Window", "Гибрид"))
        self.button_scheme.setText(_translate("Window", "Схема"))
        self.button_sat.setText(_translate("Window", "Спутник"))
